-- View: _custom.saleshistory

-- DROP VIEW _custom.saleshistory;

CREATE OR REPLACE VIEW _custom.saleshistory AS 
 SELECT data.cohist_id,
    data.cohist_cust_id,
    data.cohist_itemsite_id,
    data.cohist_shipdate,
    data.cohist_shipvia,
    data.cohist_ordernumber,
    data.cohist_orderdate,
    data.cohist_invcnumber,
    data.cohist_invcdate,
    data.cohist_qtyshipped,
    data.cohist_unitprice,
    data.cohist_shipto_id,
    data.cohist_salesrep_id,
    data.cohist_duedate,
    data.cohist_imported,
    data.cohist_billtoname,
    data.cohist_billtoaddress1,
    data.cohist_billtoaddress2,
    data.cohist_billtoaddress3,
    data.cohist_billtocity,
    data.cohist_billtostate,
    data.cohist_billtozip,
    data.cohist_shiptoname,
    data.cohist_shiptoaddress1,
    data.cohist_shiptoaddress2,
    data.cohist_shiptoaddress3,
    data.cohist_shiptocity,
    data.cohist_shiptostate,
    data.cohist_shiptozip,
    data.cohist_commission,
    data.cohist_commissionpaid,
    data.cohist_unitcost,
    data.cohist_misc_type,
    data.cohist_misc_descrip,
    data.cohist_misc_id,
    data.cohist_doctype,
    data.cohist_promisedate,
    data.cohist_ponumber,
    data.cohist_curr_id,
    data.cohist_sequence,
    data.cohist_taxtype_id,
    data.cohist_taxzone_id,
    data.cohist_saletype_id,
    data.cohist_shipzone_id,
    data.cohist_cohead_ccpay_id,
    data.cohead_id,
    data.cust_id,
    data.cust_number,
    data.cust_name,
    data.cust_curr_id,
    data.custtype_id,
    data.custtype_code,
    data.custtype_descrip,
    data.salesrep_id,
    data.salesrep_number,
    data.salesrep_name,
    data.shipzone_id,
    data.shipzone_name,
    data.shipzone_descrip,
    data.saletype_code,
    data.saletype_descr,
    data.itemsite_id,
    data.warehous_id,
    data.warehous_code,
    data.warehous_descrip,
    data.item_id,
    data.item_number,
    data.item_descrip1,
    data.item_descrip2,
    data.itemdescription,
    data.itemnumber,
    data.prodcat_id,
    data.prodcat_code,
    data.classcode_id,
    data.classcode_code,
    data.basecommission,
    data.baseunitprice,
    data.custunitprice,
    round(data.cohist_qtyshipped * data.cohist_unitprice, 2) AS extprice,
    round(data.cohist_qtyshipped * data.baseunitprice, 2) AS baseextprice,
    round(data.cohist_qtyshipped * data.custunitprice, 2) AS custextprice,
    round(data.cohist_qtyshipped * data.cohist_unitcost, 4) AS extcost,
    round(data.cohist_qtyshipped * data.baseunitprice - data.cohist_qtyshipped * data.cohist_unitcost, 2) AS margin,
        CASE
            WHEN round(data.cohist_qtyshipped * data.baseunitprice, 2) > 0.0 THEN round(data.cohist_qtyshipped * data.baseunitprice - data.cohist_qtyshipped * data.cohist_unitcost, 2) / round(data.cohist_qtyshipped * data.baseunitprice, 2)
            ELSE 0.0
        END AS marginpercent,
    currconcat(data.cohist_curr_id) AS currabbr,
    'qty'::text AS cohist_qtyshipped_xtnumericrole,
    'salesprice'::text AS cohist_unitprice_xtnumericrole,
    'salesprice'::text AS baseunitprice_xtnumericrole,
    'curr'::text AS custunitprice_xtnumericrole,
    'curr'::text AS custextprice_xtnumericrole,
    'curr'::text AS extprice_xtnumericrole,
    'curr'::text AS baseextprice_xtnumericrole,
    'cost'::text AS cohist_unitcost_xtnumericrole,
    'curr'::text AS extcost_xtnumericrole,
    'curr'::text AS margin_xtnumericrole,
    'percent'::text AS marginpercent_xtnumericrole,
    'curr'::text AS cohist_commission_xtnumericrole,
    'curr'::text AS basecommission_xtnumericrole
   FROM ( SELECT cohist.cohist_id,
            cohist.cohist_cust_id,
            cohist.cohist_itemsite_id,
            cohist.cohist_shipdate,
            cohist.cohist_shipvia,
            cohist.cohist_ordernumber,
            cohist.cohist_orderdate,
            cohist.cohist_invcnumber,
            cohist.cohist_invcdate,
            cohist.cohist_qtyshipped,
            cohist.cohist_unitprice,
            cohist.cohist_shipto_id,
            cohist.cohist_salesrep_id,
            cohist.cohist_duedate,
            cohist.cohist_imported,
            cohist.cohist_billtoname,
            cohist.cohist_billtoaddress1,
            cohist.cohist_billtoaddress2,
            cohist.cohist_billtoaddress3,
            cohist.cohist_billtocity,
            cohist.cohist_billtostate,
            cohist.cohist_billtozip,
            cohist.cohist_shiptoname,
            cohist.cohist_shiptoaddress1,
            cohist.cohist_shiptoaddress2,
            cohist.cohist_shiptoaddress3,
            cohist.cohist_shiptocity,
            cohist.cohist_shiptostate,
            cohist.cohist_shiptozip,
            cohist.cohist_commission,
            cohist.cohist_commissionpaid,
            cohist.cohist_unitcost,
            cohist.cohist_misc_type,
            cohist.cohist_misc_descrip,
            cohist.cohist_misc_id,
            cohist.cohist_doctype,
            cohist.cohist_promisedate,
            cohist.cohist_ponumber,
            cohist.cohist_curr_id,
            cohist.cohist_sequence,
            cohist.cohist_taxtype_id,
            cohist.cohist_taxzone_id,
            cohist.cohist_saletype_id,
            cohist.cohist_shipzone_id,
            cohist.cohist_cohead_ccpay_id,
            COALESCE(cohead.cohead_id, (-1)) AS cohead_id,
            custinfo.cust_id,
            custinfo.cust_number,
            custinfo.cust_name,
            custinfo.cust_curr_id,
            custtype.custtype_id,
            custtype.custtype_code,
            custtype.custtype_descrip,
            salesrep.salesrep_id,
            salesrep.salesrep_number,
            salesrep.salesrep_name,
            shipzone.shipzone_id,
            shipzone.shipzone_name,
            shipzone.shipzone_descrip,
            saletype.saletype_code,
            saletype.saletype_descr,
            itemsite.itemsite_id,
            site.warehous_id,
            site.warehous_code,
            site.warehous_descrip,
            item.item_id,
            item.item_number,
            item.item_descrip1,
            item.item_descrip2,
            (item.item_descrip1 || ' '::text) || item.item_descrip2 AS itemdescription,
            COALESCE(item.item_number, cohist.cohist_misc_descrip) AS itemnumber,
            prodcat.prodcat_id,
            prodcat.prodcat_code,
            classcode.classcode_id,
            classcode.classcode_code,
            currtobase(cohist.cohist_curr_id, cohist.cohist_commission, cohist.cohist_invcdate) AS basecommission,
            currtobase(cohist.cohist_curr_id, cohist.cohist_unitprice, cohist.cohist_invcdate) AS baseunitprice,
            currtocurr(cohist.cohist_curr_id, custinfo.cust_curr_id, cohist.cohist_unitprice, cohist.cohist_invcdate) AS custunitprice
           FROM cohist
             JOIN custinfo ON custinfo.cust_id = cohist.cohist_cust_id
             LEFT JOIN cohead ON cohead.cohead_number = cohist.cohist_ordernumber
             LEFT JOIN custtype ON custtype.custtype_id = custinfo.cust_custtype_id
             LEFT JOIN salesrep ON salesrep.salesrep_id = cohist.cohist_salesrep_id
             LEFT JOIN shiptoinfo ON shiptoinfo.shipto_id = cohist.cohist_shipto_id
             LEFT JOIN shipzone ON shipzone.shipzone_id = shiptoinfo.shipto_shipzone_id
             LEFT JOIN saletype ON saletype.saletype_id = cohist.cohist_saletype_id
             JOIN itemsite ON itemsite.itemsite_id = cohist.cohist_itemsite_id
             JOIN site() site(warehous_id, warehous_code, warehous_descrip, warehous_fob, warehous_active, warehous_counttag_prefix, warehous_counttag_number, warehous_bol_prefix, warehous_bol_number, warehous_shipping, warehous_useslips, warehous_usezones, warehous_aislesize, warehous_aislealpha, warehous_racksize, warehous_rackalpha, warehous_binsize, warehous_binalpha, warehous_locationsize, warehous_locationalpha, warehous_enforcearbl, warehous_default_accnt_id, warehous_shipping_commission, warehous_cntct_id, warehous_addr_id, warehous_transit, warehous_shipform_id, warehous_shipvia_id, warehous_shipcomments, warehous_costcat_id, warehous_sitetype_id, warehous_taxzone_id, warehous_sequence) ON site.warehous_id = itemsite.itemsite_warehous_id
             JOIN item ON item.item_id = itemsite.itemsite_item_id
             JOIN prodcat ON prodcat.prodcat_id = item.item_prodcat_id
             JOIN classcode ON classcode.classcode_id = item.item_classcode_id
			 LEFT JOIN invchead ON cohist.cohist_invcnumber = invchead.invchead_invcnumber 
			WHERE COALESCE(cohead.cohead_custponumber, invchead.invchead_ponumber) <> 'INVALID'::text) data;

ALTER TABLE _custom.saleshistory
  OWNER TO admin;
GRANT ALL ON TABLE _custom.saleshistory TO admin;
GRANT ALL ON TABLE _custom.saleshistory TO xtrole;
COMMENT ON VIEW _custom.saleshistory
  IS 'Single point for sales history calculations. Modified by ASSET';
